
export const dom = {
    appContainer: document.getElementById('app-container'),
    screens: document.querySelectorAll('.screen'),
    loadingOverlay: document.getElementById('loading-overlay'),
    loadingText: document.getElementById('loading-text'),
    toastContainer: document.getElementById('toast-container'),
    mainContent: document.querySelector('main'),
    quizTimer: document.getElementById('quiz-timer'),
    questionCounter: document.getElementById('question-counter'),
    quizHintBtn: document.getElementById('hint-btn'),
    quizProgressBar: document.getElementById('quiz-progress-bar'),
    questionText: document.getElementById('question-text'),
    optionsContainer: document.getElementById('options-container'),
    webGLContainer: document.getElementById('webgl-container'),
    topicGrid: document.getElementById('topic-grid'),
    levelGrid: document.getElementById('level-grid'),
    levelTopicTitle: document.getElementById('level-topic-title'),
    levelProgressBar: document.getElementById('level-progress-bar'),
    levelProgressText: document.getElementById('level-progress-text'),
    currentLevelText: document.getElementById('current-level-text'),
    historyLog: document.getElementById('history-log'),
    finalScoreValue: document.getElementById('final-score-value'),
    correctAnswers: document.getElementById('correct-answers'),
    incorrectAnswers: document.getElementById('incorrect-answers'),
    resultsTopicText: document.getElementById('results-topic-text'),
    resultsActionButtons: document.getElementById('results-action-buttons'),
    unlockMessage: document.getElementById('unlock-message'),
    logo: document.querySelector('.logo'),
    resetProgressBtn: document.getElementById('reset-progress-btn'),
    mobileNavItems: document.querySelectorAll('.mobile-nav .nav-item'),
};
